### ISSUE TITLE
文档打错字了似乎

### ISSUE THREAD

**Issue by 1411430556** [hangjob/vue-bag-admin#12]
https://vite.itnavs.com/doc/guide/duce.html#:~:text=env.development%20%20%20%20%23-,%E5%BC%80%E5%8F%91%E9%99%8C%E7%94%9F,-vite%0A.env.production
如图：
![image](https://github.com/hangjob/vue-bag-admin/assets/67215517/c480a187-1d75-4e63-b5fa-f0c11492bbee)

**Comment by hangjob** [comment]
已更新版文档

**Comment by 1411430556** [comment]
> 已更新版文档

好的
